package com.dicoding.cocktailapps.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF7F4894)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF9D8FF)
val md_theme_light_onPrimaryContainer = Color(0xFF320046)
val md_theme_light_secondary = Color(0xFFA23855)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9DF)
val md_theme_light_onSecondaryContainer = Color(0xFF3F0016)
val md_theme_light_tertiary = Color(0xFFB2283C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDADA)
val md_theme_light_onTertiaryContainer = Color(0xFF40000B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF3F0300)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF3F0300)
val md_theme_light_surfaceVariant = Color(0xFFEBDFE9)
val md_theme_light_onSurfaceVariant = Color(0xFF4C444D)
val md_theme_light_outline = Color(0xFF7D747D)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDE9)
val md_theme_light_inverseSurface = Color(0xFF5F150A)
val md_theme_light_inversePrimary = Color(0xFFECB1FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF7F4894)
val md_theme_light_outlineVariant = Color(0xFFCEC3CD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFECB1FF)
val md_theme_dark_onPrimary = Color(0xFF4C1662)
val md_theme_dark_primaryContainer = Color(0xFF652F7A)
val md_theme_dark_onPrimaryContainer = Color(0xFFF9D8FF)
val md_theme_dark_secondary = Color(0xFFFFB1C0)
val md_theme_dark_onSecondary = Color(0xFF650429)
val md_theme_dark_secondaryContainer = Color(0xFF83203E)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9DF)
val md_theme_dark_tertiary = Color(0xFFFFB3B5)
val md_theme_dark_onTertiary = Color(0xFF680018)
val md_theme_dark_tertiaryContainer = Color(0xFF900827)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDADA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF3F0300)
val md_theme_dark_onBackground = Color(0xFFFFDAD4)
val md_theme_dark_surface = Color(0xFF3F0300)
val md_theme_dark_onSurface = Color(0xFFFFDAD4)
val md_theme_dark_surfaceVariant = Color(0xFF4C444D)
val md_theme_dark_onSurfaceVariant = Color(0xFFCEC3CD)
val md_theme_dark_outline = Color(0xFF988E97)
val md_theme_dark_inverseOnSurface = Color(0xFF3F0300)
val md_theme_dark_inverseSurface = Color(0xFFFFDAD4)
val md_theme_dark_inversePrimary = Color(0xFF7F4894)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFECB1FF)
val md_theme_dark_outlineVariant = Color(0xFF4C444D)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF22092C)
